#!/usr/bin/env python

from multiprocessing import Lock, Pool, cpu_count
from functools import partial
from numpy import *
from pytes import *

def main(N, fwhm, noise, bits, sps, t, prefix, batch=1000):
    
    print "Simulating %d pulses/noises. This takes bit long time..." % N
    
    # Start sub-processes
    result_list = []
    _N = N
    pool = Pool(cpu_count())
    lock = Lock()
    while _N > batch:
        result_list.append(pool.apply_async(Simulation.simulate, args=(batch, fwhm), kwds={'noise':noise, 'sps':sps, 't':t}))
        _N -= batch
    
    if _N > 0:
        result_list.append(pool.apply_async(Simulation.simulate, args=(_N, fwhm), kwds={'noise':noise, 'sps':sps, 't':t}))
    
    pool.close()
    pool.join()
    
    print "Saving FITS files."
    results = [ r.get() for r in result_list ]
    Util.savefits(vstack(asarray(results)[:,0,:,:]), prefix+"p.fits", sps=sps, bits=bits)
    Util.savefits(vstack(asarray(results)[:,1,:,:]), prefix+"n.fits", sps=sps, bits=bits, noise=True)
    
    return 0

def usage(prog, N, prefix, noise, fwhm, bits, sps, t):
    print """Usage: %s [options]

Options:
    -c counts
        Desired number of pulses and noises. (Default: %d)
    -p prefix
        Filename prefix for pulse and noise FITS file. (Default: %s)
    -n noise
        White noise level in V/srHz. (Default: %.2e V/srHz)
    -e fwhm
        Energy resolution of line model in eV. (Default: %.2f eV)
    -b bits
        Desired number of bits for virtual ADC. (Default: %d bits)
    -s sps
        Sampling per second for dummy pulse/noise. (Default: %.2e sps)
    -t time
        Sampling time for dummy pulse/noise. (Default: %.2e s)
    -h
        Show this usage.""" % (prog, N, prefix, noise, fwhm, bits, sps, t)

if __name__ == '__main__':
    
    import sys, getopt
    
    opts, params = getopt.getopt(sys.argv[1:], 'h?c:p:n:e:b:s:t:', ['help'])
    
    # Initialize
    N = 1000
    prefix = "dummy"
    noise = 3e-6
    fwhm = 0
    bits = 16
    sps = 1e6
    t = 2e-3
    
    for o, a in opts:
        if o == "-c":
            N = int(a)
        if o == "-p":
            prefix = a
        if o == "-n":
            noise = float(a)
        if o == "-e":
            fwhm = float(a)
        if o == "-b":
            bits = int(a)
        if o == "-s":
            sps = float(a)
        if o == "-t":
            t = float(a)
        if o in ("-h", "-?", "--help"):
            usage(sys.argv[0], N, prefix, noise, fwhm, bits, sps, t)
            exit()
 
    main(N, fwhm, noise, bits, sps, t, prefix)